/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Latihan5;

import main.java.Latihan5.DeserializeXML;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        main.java.Latihan5.DeserializeXML classUnderTest = new DeserializeXML();
        assertNotNull("app should have a greeting", classUnderTest.getClass());
    }
}
